### ISSUE TITLE
Unable to stop the stream: 

### ISSUE THREAD

**Issue by deepakcg97** [niladri30/Fire-detection-using-Python#1]
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x100eb50] moov atom not found
Unable to stop the stream: Inappropriate ioctl for device

**Comment by niladri30** [comment]
I think your video file is corrupted due to which this exception is happening : moov atom not found.
I have tested it on live streaming and it worked, it seems to be ffmpeg problem in your opencv setup. Please check: https://stackoverflow.com/questions/42562876/opencv3-error-unable-to-stop-the-stream-inappropriate-ioctl-for-device
